
package Interface;

import Conexao.*;
import Tabelas.*;
import java.sql.*;
import javax.swing.*;
import java.lang.NullPointerException;

public class Telamdi extends javax.swing.JFrame {
    Statement stmt = Conexao.stmt;
     

    public Telamdi() {
        initComponents();
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cadAluno = new javax.swing.JMenuItem();
        Consulta_al = new javax.swing.JMenuItem();
        Excluiraluno = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Cadprof = new javax.swing.JMenuItem();
        consulprof = new javax.swing.JMenuItem();
        excprof = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        caddisc = new javax.swing.JMenuItem();
        cnsuldisc = new javax.swing.JMenuItem();
        excdisc = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        cadnotas = new javax.swing.JMenuItem();
        excnotas = new javax.swing.JMenuItem();
        consulnotas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu3.setText("jMenu3");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/login.png"))); // NOI18N

        jDesktopPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        jMenu1.setText("Usuario");

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jMenuItem16.setText("Cadastrar");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem16);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifier.png"))); // NOI18N
        jMenuItem17.setText("Consultar");
        jMenu1.add(jMenuItem17);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jMenuItem18.setText("Excluir");
        jMenu1.add(jMenuItem18);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group.png"))); // NOI18N
        jMenu2.setText("Alunos");

        cadAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        cadAluno.setText("Cadastrar");
        cadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(cadAluno);

        Consulta_al.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifier.png"))); // NOI18N
        Consulta_al.setText("Consultar");
        Consulta_al.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta_alActionPerformed(evt);
            }
        });
        jMenu2.add(Consulta_al);

        Excluiraluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        Excluiraluno.setText("Excluir");
        Excluiraluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluiralunoActionPerformed(evt);
            }
        });
        jMenu2.add(Excluiraluno);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_edit.png"))); // NOI18N
        jMenu4.setText("Professores");

        Cadprof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        Cadprof.setText("Cadastrar");
        Cadprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadprofActionPerformed(evt);
            }
        });
        jMenu4.add(Cadprof);

        consulprof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifier.png"))); // NOI18N
        consulprof.setText("Consultar");
        consulprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulprofActionPerformed(evt);
            }
        });
        jMenu4.add(consulprof);

        excprof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        excprof.setText("Excluir");
        excprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excprofActionPerformed(evt);
            }
        });
        jMenu4.add(excprof);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/book_add.png"))); // NOI18N
        jMenu5.setText("Disciplina");

        caddisc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        caddisc.setText("Cadastrar");
        caddisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddiscActionPerformed(evt);
            }
        });
        jMenu5.add(caddisc);

        cnsuldisc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifier.png"))); // NOI18N
        cnsuldisc.setText("Consultar");
        cnsuldisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnsuldiscActionPerformed(evt);
            }
        });
        jMenu5.add(cnsuldisc);

        excdisc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        excdisc.setText("Excluir");
        excdisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excdiscActionPerformed(evt);
            }
        });
        jMenu5.add(excdisc);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar_edit.png"))); // NOI18N
        jMenu6.setText("Notas");

        cadnotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        cadnotas.setText("Cadastrar");
        cadnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadnotasActionPerformed(evt);
            }
        });
        jMenu6.add(cadnotas);

        excnotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifier.png"))); // NOI18N
        excnotas.setText("Consultar");
        excnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excnotasActionPerformed(evt);
            }
        });
        jMenu6.add(excnotas);

        consulnotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        consulnotas.setText("Excluir");
        consulnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulnotasActionPerformed(evt);
            }
        });
        jMenu6.add(consulnotas);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/database.png"))); // NOI18N
        jMenu7.setText("Backup");

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/database_go.png"))); // NOI18N
        jMenuItem20.setText("Executar Backup");
        jMenu7.add(jMenuItem20);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jMenu8.setText("Sair");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jMenuItem4.setText("Sair");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem4);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAlunoActionPerformed
        // TODO add your handling code here:
        Cadastro_alunopainel telauser= new Cadastro_alunopainel();
        jDesktopPane1.add(telauser);
        telauser.setVisible(true);
      
    }//GEN-LAST:event_cadAlunoActionPerformed

    private void CadprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadprofActionPerformed
        // TODO add your handling code here:
        Cadastro_professorpainel telacadprof = new Cadastro_professorpainel();
        jDesktopPane1.add(telacadprof);
        telacadprof.setVisible(true);
    }//GEN-LAST:event_CadprofActionPerformed

    private void caddiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddiscActionPerformed
        // TODO add your handling code here:
        Cadastro_discpainel teladisc= new Cadastro_discpainel();
        jDesktopPane1.add(teladisc);
        teladisc.setVisible(true);
    }//GEN-LAST:event_caddiscActionPerformed

    private void cadnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadnotasActionPerformed
        // TODO add your handling code here:
        Cadastro_notaspainel telanota = new Cadastro_notaspainel();
        jDesktopPane1.add(telanota);
        telanota.setVisible(true);
       
 
    }//GEN-LAST:event_cadnotasActionPerformed

    private void ExcluiralunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluiralunoActionPerformed
        // TODO add your handling code here:
        Excluir_aluno telaex= new Excluir_aluno();
        jDesktopPane1.add(telaex);
        telaex.setVisible(true);
    }//GEN-LAST:event_ExcluiralunoActionPerformed

    private void excprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excprofActionPerformed
        // TODO add your handling code here:
        Excluir_prof telaexprof = new Excluir_prof();
        jDesktopPane1.add(telaexprof);
        telaexprof.setVisible(true);
    }//GEN-LAST:event_excprofActionPerformed

    private void Consulta_alActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta_alActionPerformed
        // TODO add your handling code here:
        Pesquisa_al telapes1= new Pesquisa_al();
        jDesktopPane1.add(telapes1);
        telapes1.setVisible(true);
    }//GEN-LAST:event_Consulta_alActionPerformed

    private void consulprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulprofActionPerformed
        // TODO add your handling code here:
        Pesquisa_prof telapesp= new Pesquisa_prof();
        jDesktopPane1.add(telapesp);
        telapesp.setVisible(true);
    }//GEN-LAST:event_consulprofActionPerformed

    private void cnsuldiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnsuldiscActionPerformed
        // TODO add your handling code here:
        Pesquisa_disc teladiscp = new Pesquisa_disc();
        jDesktopPane1.add(teladiscp);
        teladiscp.setVisible(true);
    }//GEN-LAST:event_cnsuldiscActionPerformed

    private void excnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excnotasActionPerformed
        // TODO add your handling code here:
        Pesquisa_notas telanotap= new Pesquisa_notas();
        jDesktopPane1.add(telanotap);
        telanotap.setVisible(true);
    }//GEN-LAST:event_excnotasActionPerformed

    private void excdiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excdiscActionPerformed
        // TODO add your handling code here:
        Excluir_disciplina telaexd= new Excluir_disciplina();
        jDesktopPane1.add(telaexd);
        telaexd.setVisible(true);
    }//GEN-LAST:event_excdiscActionPerformed

    private void consulnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulnotasActionPerformed
        // TODO add your handling code here:
        Excluir_notas telaexn= new Excluir_notas();
        jDesktopPane1.add(telaexn);
        telaexn.setVisible(true);
    }//GEN-LAST:event_consulnotasActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        Cadastro_usu telacadu = new Cadastro_usu();
        jDesktopPane1.add(telacadu);
        telacadu.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        //exit telaexit = new exit();
        //jDesktopPane1.add(telaexit);
        //telaexit.setVisible(true);
        //dispose();
         Conexao con = new Conexao();
        con.desconectar();
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telamdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telamdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telamdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telamdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telamdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cadprof;
    private javax.swing.JMenuItem Consulta_al;
    private javax.swing.JMenuItem Excluiraluno;
    private javax.swing.JMenuItem cadAluno;
    private javax.swing.JMenuItem caddisc;
    private javax.swing.JMenuItem cadnotas;
    private javax.swing.JMenuItem cnsuldisc;
    private javax.swing.JMenuItem consulnotas;
    private javax.swing.JMenuItem consulprof;
    private javax.swing.JMenuItem excdisc;
    private javax.swing.JMenuItem excnotas;
    private javax.swing.JMenuItem excprof;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
